export const Users = [
    {
        id: 0,
        icon: "https://store-images.s-microsoft.com/image/apps.58521.13510798887167234.713cc0e4-e4a7-4f7c-8cde-9c6a53872b1d.539a5fdf-76a3-486f-bb0f-d2dce82923cc?mode=scale&q=90&h=270&w=270&background=%230078D7",
        label: "instagram",
        subLabel: "Instagram",
        info: "instagram Official Account",
        followed: true,
    },
    {
        id: 1,
        icon: "https://i.dailymail.co.uk/i/pix/2016/10/05/05/391BDF0200000578-3822458-Glamorous_A_new_Instagram_profile_appeared_on_the_site_in_August-a-21_1475640329592.jpg",
        label: "camila_cabello",
        subLabel: "camila",
        info: "Instagram recommended",
        followed: false,

    },
    {
        id: 2,
        icon: "https://pbs.twimg.com/profile_images/723309255231561730/-Xl86asp_400x400.jpg",
        label: "aliaabhatt",
        subLabel: "Alia Bhatt",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 3,
        icon: "https://i.dailymail.co.uk/i/pix/2016/03/01/12/31BB3AFF00000578-3471019-image-a-77_1456835021704.jpg",
        label: "Bahtiyorjon Arslonbekov",
        subLabel: "Baakhtee",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 4,
        icon: "https://www.inkedmag.com/.image/t_share/MTU5MDMyMjI1NTU0OTY2Mjk2/liam-payne---facebook.jpg",
        label: "Javohirbek Khoshimov",
        subLabel: "Jakha",
        info: "Instagram recommended",

    },
    {
        id: 5,
        icon: "https://36la3t3jc3744v5lp3jawi51-wpengine.netdna-ssl.com/wp-content/uploads/2020/03/member-profile-mike-jonas.jpg",
        label: "Azizbek",
        subLabel: "Azi",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 6,
        icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBKl8PFoYK2s9_5FEy5iUtdtMWmK-HwWpysc1P5jDWSCU3eTE646mVo1gfXSk8_yg_GBM&usqp=CAU",
        label: "Oyatillo",
        subLabel: "Huhu",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 7,
        icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5lGEoyvejoCFQmhw2o0Z4OFzQ76LzVgCyfgWWWuN-C9DKrAT_x6VyXVefFMKoJrkLLoI&usqp=CAU",
        label: "Oyatillo",
        subLabel: "Jigar",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 8,
        icon: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        label: "Bobomurod",
        subLabel: "Bobo",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 9,
        icon: "https://miro.medium.com/max/395/1*n2DxqTwROXZmkLUjTD4uXQ.jpeg",
        label: "Lolila Enric",
        subLabel: "Lolita",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 10,
        icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBHIrk92KiatrR44PxA-c4AmN9FEUme72kB1uzrhCOy4qX3D3W2rmBwJxYqj4IwZ8NNb4&usqp=CAU",
        label: "Murodjon Boynazarov",
        subLabel: "Murodchik",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 11,
        icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpG4GuR3swgkYAW2Hl54b5BpyTtHr-bbDINZbGS9S5GopkwCT-VWWYdqe3xDs43a8VgPE&usqp=CAU",
        label: "Asasin Hudoyberganov",
        subLabel: "Assasin",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 12,
        icon: "https://pbs.twimg.com/profile_images/830557958404767744/wxA-kVsR_400x400.jpg",
        label: "Nunuka",
        subLabel: "Nunka",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 13,
        icon: "https://i2-prod.mirror.co.uk/incoming/article8981461.ece/ALTERNATES/s615b/Instagram8.jpg",
        label: "Lalaku",
        subLabel: "Lalaku",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 14,
        icon: "https://denverjewishchamber.com/wp-content/uploads/2018/10/business-woman-profile-picture-6-e1539213049252.jpg",
        label: "Dinara Petrov",
        subLabel: "Petrov",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 15,
        icon: "https://thegreenprogram.com/uploads/attachments/cisc7g4v50042gzgzfe1a15j9-charles-white1.100.0.399.399.full.jpg",
        label: "Maxim",
        subLabel: "Maxim",
        info: "Instagram recommended",
        followed: false,
    },
]