export const Users = [
    {
        id: 0,
        icon: "https://store-images.s-microsoft.com/image/apps.58521.13510798887167234.713cc0e4-e4a7-4f7c-8cde-9c6a53872b1d.539a5fdf-76a3-486f-bb0f-d2dce82923cc?mode=scale&q=90&h=270&w=270&background=%230078D7",
        label: "instagram",
        subLabel: "Instagram",
        info: "instagram Official Account",
        followed: true,
    },
    {
        id: 1,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "camila_cabello",
        subLabel: "camila",
        info: "Instagram recommended",
        followed: false,

    },
    {
        id: 2,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "aliaabhatt",
        subLabel: "Alia Bhatt",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 3,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 4,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",

    },
    {
        id: 5,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 6,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 7,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 8,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 9,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 10,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 11,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 12,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 13,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 14,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },
    {
        id: 15,
        icon: "https://img.17qq.com/images/wuuheax.jpeg",
        label: "",
        subLabel: "",
        info: "Instagram recommended",
        followed: false,
    },

]